# app/routers/roadmap.py
import logging

from fastapi import APIRouter, Depends, HTTPException, status
from sqlmodel import Session, select
from typing import List

from app.database import get_session
from app.models import LearningRoadmap, DSAProblem, DSATopic, ProblemAttempt
from app.routers.auth import get_current_user, User
from app.services import ai_service
from app.services.ai_service import AIUnavailableError, AIGenerationError
from app.services.progress_service import compute_topic_proficiency
from app.services.rate_limit import RateLimiter

router = APIRouter(prefix="/roadmap", tags=["Roadmap"])

logger = logging.getLogger(__name__)

# Roadmap generation is a Gemini call — throttle per IP like the other AI routes.
roadmap_limiter = RateLimiter("ai_roadmap", limit=10, window_seconds=60)


def _ai_error(exc: Exception) -> HTTPException:
    """Map AI failures to honest HTTP errors without leaking provider detail."""
    if isinstance(exc, AIUnavailableError):
        return HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail=str(exc)
        )
    logger.error("Roadmap AI generation failed: %s", exc, exc_info=True)
    return HTTPException(
        status_code=status.HTTP_502_BAD_GATEWAY,
        detail="AI response could not be generated right now. Please try again.",
    )


@router.get("", response_model=List[LearningRoadmap])
def get_roadmaps(
    session: Session = Depends(get_session),
    current_user: User = Depends(get_current_user),
):
    """Retrieve all learning roadmaps generated by the user"""
    statement = (
        select(LearningRoadmap)
        .where(LearningRoadmap.user_id == current_user.id)
        .order_by(LearningRoadmap.created_on.desc())
    )

    return session.exec(statement).all()


@router.post(
    "/generate",
    response_model=LearningRoadmap,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(roadmap_limiter)],
)
def generate_roadmap(
    session: Session = Depends(get_session),
    current_user: User = Depends(get_current_user),
):
    """Generate a 7-day personalized DSA roadmap via Gemini, grounded on the
    user's real weak topics and unsolved platform problems."""
    weak_topics = compute_topic_proficiency(session, current_user.id)

    # Candidate problems: active and not yet solved by this user.
    solved_ids = set(
        session.exec(
            select(ProblemAttempt.problem_id)
            .where(
                ProblemAttempt.user_id == current_user.id,
                ProblemAttempt.status == "Correct",
            )
            .distinct()
        ).all()
    )
    problems = session.exec(
        select(DSAProblem).where(DSAProblem.is_active == True)  # noqa: E712
    ).all()
    # Resolve all topic names in one query rather than per-problem.
    topic_names = {t.id: t.name for t in session.exec(select(DSATopic)).all()}
    candidates = []
    for p in problems:
        if p.id in solved_ids:
            continue
        candidates.append(
            {
                "id": p.id,
                "title": p.title,
                "difficulty": p.difficulty,
                "topic": topic_names.get(p.topic_id, "General"),
            }
        )

    if not candidates:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No unsolved problems available to build a roadmap from.",
        )

    try:
        roadmap_data = ai_service.generate_roadmap(
            weak_topics=[
                {"topic": t["topic_name"], "proficiency": t["score"]}
                for t in weak_topics
            ]
            or [
                {"topic": "No attempts yet — start with fundamentals", "proficiency": 0}
            ],
            candidate_problems=candidates,
        )
    except (AIUnavailableError, AIGenerationError) as exc:
        raise _ai_error(exc)

    new_roadmap = LearningRoadmap(
        user_id=current_user.id,
        title=roadmap_data.get("title", "7-Day DSA Recovery Plan"),
        roadmap_data=roadmap_data,
    )

    session.add(new_roadmap)
    session.commit()
    session.refresh(new_roadmap)
    return new_roadmap
