<script lang="ts">
	import { api } from '$lib/api';
	import { Button } from '$lib/components/ui/button';
	import { Card } from '$lib/components/ui/card';

	interface QuizQuestion {
		id: number;
		position: number;
		kind: string; // 'mcq' | 'short_answer' | 'dry_run' | 'complexity'
		question: string;
		options?: string[] | null;
	}

	interface QuizResultItem {
		question_id: number;
		correct: boolean;
		your_answer: string;
		expected?: string | null;
		explanation: string;
	}

	interface QuizGradeResponse {
		score: number;
		total: number;
		results: QuizResultItem[];
	}

	let {
		noteId,
		onQuizCompleted
	} = $props<{
		noteId: number;
		onQuizCompleted: (score: number, total: number) => void;
	}>();

	let questions = $state<QuizQuestion[]>([]);
	let loading = $state(true);
	let error = $state('');
	let generating = $state(false);

	let currentQuestionIndex = $state(0);
	let answers = $state<Record<number, string>>({}); // question_id -> answer text

	// Submit and result state
	let submitting = $state(false);
	let result = $state<QuizGradeResponse | null>(null);

	$effect(() => {
		if (noteId) {
			loadQuiz();
		}
	});

	async function loadQuiz() {
		loading = true;
		error = '';
		result = null;
		answers = {};
		currentQuestionIndex = 0;
		try {
			// Try fetching questions
			questions = await api<QuizQuestion[]>(`/topic-notes/${noteId}/quiz`);
		} catch (e: any) {
			if (e.status === 404) {
				// No quiz questions exist yet, we will offer to generate them
				questions = [];
			} else {
				error = e.message || 'Failed to load quiz questions.';
			}
		} finally {
			loading = false;
		}
	}

	async function handleGenerateQuiz() {
		generating = true;
		error = '';
		try {
			await api(`/topic-notes/${noteId}/quiz/generate`, { method: 'POST' });
			await loadQuiz();
		} catch (e: any) {
			error = e.message || 'Failed to generate quiz.';
		} finally {
			generating = false;
		}
	}

	async function handleSubmit() {
		// Verify all questions have an answer
		const unanswered = questions.filter(q => !answers[q.id]);
		if (unanswered.length > 0) {
			alert(`Please answer all questions before submitting. (Unanswered: ${unanswered.map(q => q.position).join(', ')})`);
			return;
		}

		submitting = true;
		error = '';
		try {
			const submissionAnswers = questions.map(q => ({
				question_id: q.id,
				answer: answers[q.id]
			}));

			result = await api<QuizGradeResponse>(`/topic-notes/${noteId}/quiz/submit`, {
				method: 'POST',
				body: JSON.stringify({ answers: submissionAnswers })
			});

			onQuizCompleted(result.score, result.total);
		} catch (e: any) {
			error = e.message || 'Failed to submit quiz.';
		} finally {
			submitting = false;
		}
	}

	function selectMcqOption(qId: number, idx: number) {
		answers[qId] = String(idx);
	}
</script>

<div class="flex flex-col gap-5 w-full">
	{#if loading}
		<div class="flex flex-col items-center justify-center p-12 gap-3 bg-white border border-slate-200 rounded-2xl">
			<div class="animate-spin rounded-full h-8 w-8 border-4 border-slate-200 border-t-blue-600"></div>
			<p class="text-xs text-slate-500 font-medium">Opening quiz package...</p>
		</div>
	{:else if error}
		<div class="bg-rose-50 border border-rose-200 rounded-2xl p-4 text-xs text-rose-700 leading-relaxed">
			<strong>Error:</strong> {error}
		</div>
	{:else if questions.length === 0}
		<!-- Empty state: Offer to generate quiz -->
		<Card class="border-slate-200 bg-white p-8 text-center flex flex-col items-center justify-center gap-4">
			<div class="w-12 h-12 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center font-bold text-lg">📝</div>
			<div class="flex flex-col gap-1 max-w-[340px]">
				<h3 class="font-bold text-slate-800 text-sm">Interactive Topic Quiz</h3>
				<p class="text-slate-500 text-[11px] leading-relaxed">
					Test your understanding on edge cases, complexities, and code templates. Questions are dynamically generated by Gemini.
				</p>
			</div>
			<Button class="bg-blue-600 hover:bg-blue-700 text-white text-xs h-9 px-6 font-semibold" onclick={handleGenerateQuiz} disabled={generating}>
				{generating ? 'Generating Quiz Questions...' : 'Generate Quiz Now'}
			</Button>
		</Card>
	{:else if result}
		<!-- Quiz Result Screen -->
		<div class="flex flex-col gap-5">
			<Card class="bg-slate-50 border border-slate-200 p-6 flex flex-col items-center justify-center text-center gap-2">
				<span class="text-[10px] font-extrabold text-slate-400 uppercase tracking-widest">Quiz Completed!</span>
				<span class="text-3xl font-extrabold text-blue-600 font-title">{result.score} / {result.total}</span>
				<span class="text-xs font-bold text-slate-600 mt-1">
					Score: {Math.round((result.score / result.total) * 100)}%
				</span>
				<Button variant="outline" size="sm" class="text-xs h-8 border-slate-200 mt-2.5" onclick={loadQuiz}>Retake Quiz</Button>
			</Card>

			<div class="flex flex-col gap-4">
				<h4 class="text-xs font-bold text-slate-800 uppercase tracking-wider">Detailed Feedback</h4>
				{#each questions as q, index}
					{@const qRes = result.results.find(r => r.question_id === q.id)}
					{#if qRes}
						<div class="border border-slate-200 rounded-2xl bg-white overflow-hidden p-5 flex flex-col gap-3 shadow-sm {qRes.correct ? 'border-emerald-100 bg-emerald-50/5' : 'border-rose-100 bg-rose-50/5'}">
							<div class="flex items-start justify-between gap-3">
								<span class="text-xs font-bold text-slate-800">Question {index + 1}: {q.question}</span>
								<span class="text-[10px] font-bold px-2 py-0.5 rounded-full {qRes.correct ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}">
									{qRes.correct ? 'Correct' : 'Incorrect'}
								</span>
							</div>

							{#if q.options}
								<div class="flex flex-col gap-1.5 pl-2">
									{#each q.options as opt, optIdx}
										{@const isUserChoice = qRes.your_answer === String(optIdx)}
										{@const isCorrectChoice = qRes.expected ? qRes.expected === String(optIdx) : isUserChoice}
										<div class="text-[11px] p-2 rounded-lg border font-medium {isCorrectChoice && !qRes.correct ? 'bg-emerald-50 border-emerald-200 text-emerald-800 font-semibold' : isUserChoice ? (qRes.correct ? 'bg-emerald-50 border-emerald-200 text-emerald-800 font-semibold' : 'bg-rose-50 border-rose-200 text-rose-800 font-semibold') : 'bg-slate-50/50 border-slate-100 text-slate-600'}">
											{optIdx + 1}. {opt}
										</div>
									{/each}
								</div>
							{:else}
								<div class="flex flex-col gap-1.5 pl-2 text-[11px]">
									<div class="bg-slate-50 border border-slate-100 p-2.5 rounded-lg text-slate-700 font-mono">
										<strong>Your answer:</strong> {qRes.your_answer}
									</div>
									{#if !qRes.correct && qRes.expected}
										<div class="bg-emerald-50 border border-emerald-100 p-2.5 rounded-lg text-emerald-800 font-mono">
											<strong>Model answer:</strong> {qRes.expected}
										</div>
									{/if}
								</div>
							{/if}

							<div class="bg-slate-100/50 border border-slate-200/50 rounded-xl p-3.5 text-[11.5px] text-slate-600 leading-relaxed">
								<strong>Explanation:</strong> {qRes.explanation}
							</div>
						</div>
					{/if}
				{/each}
			</div>
		</div>
	{:else}
		<!-- Interactive Quiz Question View -->
		{@const currentQuestion = questions[currentQuestionIndex]}
		{@const userAnswer = answers[currentQuestion.id] || ''}

		<Card class="border-slate-200 bg-white p-6 flex flex-col gap-5 shadow-sm">
			<!-- Progress Bar -->
			<div class="flex items-center justify-between text-[10px] font-bold text-slate-400">
				<span>Question {currentQuestionIndex + 1} of {questions.length}</span>
				<span class="bg-slate-100 px-2 py-0.5 rounded-full uppercase tracking-wider">{currentQuestion.kind}</span>
			</div>
			<div class="w-full bg-slate-100 h-1.5 rounded-full overflow-hidden">
				<div class="bg-blue-600 h-full transition-all duration-200" style="width: {((currentQuestionIndex + 1) / questions.length) * 100}%"></div>
			</div>

			<!-- Question Text -->
			<h3 class="text-sm font-bold text-slate-800 leading-relaxed">{currentQuestion.question}</h3>

			<!-- Answers Editor/Options -->
			{#if currentQuestion.options}
				<!-- MCQ -->
				<div class="flex flex-col gap-2">
					{#each currentQuestion.options as option, idx}
						{@const isSelected = userAnswer === String(idx)}
						<button
							onclick={() => selectMcqOption(currentQuestion.id, idx)}
							class="w-full text-left p-3.5 border rounded-xl font-semibold text-[11.5px] transition-all duration-200 {isSelected ? 'border-blue-600 bg-blue-50/70 text-blue-900 shadow-sm' : 'border-slate-200 bg-white hover:border-slate-300 hover:bg-slate-50/50 text-slate-700'}"
						>
							<div class="flex items-center gap-3">
								<span class="w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold {isSelected ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-500'}">
									{idx + 1}
								</span>
								<span>{option}</span>
							</div>
						</button>
					{/each}
				</div>
			{:else}
				<!-- Free Form Text (short_answer, complexity, dry_run) -->
				<div class="flex flex-col gap-2">
					<textarea
						bind:value={answers[currentQuestion.id]}
						placeholder="Explain your approach or detail the state values..."
						class="w-full h-24 border border-slate-200 rounded-xl p-3.5 text-xs text-slate-800 outline-none focus:border-blue-400 bg-slate-50/50"
						spellcheck="false"
					></textarea>
					<span class="text-[10px] text-slate-400 font-medium">Be concise and mathematically precise for complexity queries.</span>
				</div>
			{/if}

			<!-- Navigation controls -->
			<div class="flex items-center justify-between border-t border-slate-100 pt-4 mt-2">
				<Button
					variant="outline"
					size="sm"
					class="text-xs h-9 border-slate-200"
					onclick={() => currentQuestionIndex--}
					disabled={currentQuestionIndex === 0}
				>
					Previous
				</Button>

				{#if currentQuestionIndex === questions.length - 1}
					<Button
						class="bg-blue-600 hover:bg-blue-700 text-white text-xs h-9 px-6 font-semibold"
						onclick={handleSubmit}
						disabled={submitting}
					>
						{submitting ? 'Grading quiz...' : 'Submit Answers'}
					</Button>
				{:else}
					<Button
						variant="outline"
						size="sm"
						class="text-xs h-9 border-slate-200"
						onclick={() => currentQuestionIndex++}
						disabled={!userAnswer}
					>
						Next
					</Button>
				{/if}
			</div>
		</Card>
	{/if}
</div>
